#!/bin/bash
set -eu

cp -r .conky-vision ~/
mkdir -p ~/.cache/conky-vision

read -rp 'Enter your OpenWeatherMap API key: ' api_key

if [ -z "$api_key" ]; then
    read -rp 'Enter your locale (leave empty for default): ' locale
    sed "s|template9=\"\"|template9=\"$locale\"|" .conkyrc-noweather > ~/.conkyrc
else
    sed "s|template6=\"\"|template6=\"$api_key\"|" .conkyrc > .conkyrc-tmp

    read -rp 'Enter your city id: ' city_id
    sed -i "s|template7=\"\"|template7=\"$city_id\"|" .conkyrc-tmp

    read -rp 'Enter your unit system (default, metric, imperial): ' unit_system
    sed -i "s|template8=\"\"|template8=\"$unit_system\"|" .conkyrc-tmp

    read -rp 'Enter your locale (leave empty for default): ' locale
    sed "s|template9=\"\"|template9=\"$locale\"|" .conkyrc-tmp > ~/.conkyrc

    
    while true; do
        read -n1 -p 'Do you need the sabo-filled font? (You can customize your own font inside .conkyrc)' fontSelection
        case $fontSelection in
            [Yy]* ) cp ./fonts/Sabo-Filled.otf /usr/local/share/fonts && fc-cache -f -v; break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
    
    rm .conkyrc-tmp
fi

echo 'Installation complete. (You might have to restart your windows manager)'
